services:
  - type: web
    name: mindora-backend
    env: docker
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MINDORA_MYSQL_PWD
        sync: false

